apiVersion: v1
kind: Service
metadata:
  name: mock-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: mock-service
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
