apiVersion: v1
kind: Pod
metadata:
  name: mock-service
  labels:
    app: mock-service
spec:
  containers:
  - name: mock-service
    image: docker.io/mock-service:20210623IST
  restartPolicy: Never
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
